#!/usr/bin/env php
<?php

/*
 * Exclude this file from coding standards, since we need to define constants
 * somewhere, and I think the side-effects rule is okay to break in this one
 * case.
 *
 * @codingStandardsIgnoreFile
 */
defined('WEBDIR') or define('WEBDIR', realpath(__DIR__).'/public');
defined('APPDIR') or define('APPDIR', realpath(WEBDIR.'/..'));
defined('DATADIR') or define('DATADIR', APPDIR.'/data');
defined('TMPDIR') or define('TMPDIR', '/tmp');

require APPDIR.'/bootstrap.php';
